name: Branch Synchronization

on:
  push:
    branches:
      - develop # Trigger when `develop` branch is updated
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  sync-to-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge develop into test
        run: |
          git checkout test
          git merge develop --no-commit --no-ff --allow-unrelated-histories || echo "Merge conflicts detected."
          git commit -m "Automated sync from develop to test" || echo "Nothing to commit."
          git push origin test